import { createClient } from '@/lib/supabase/server';

// Master Tenant ID used as reference template
const MASTER_TENANT_ID = '55555555-5555-5555-5555-555555555555';

export async function provisionDefaultCategoriesForNewTenant(newTenantId: string) {
    const supabase = await createClient() as any;

    try {
        // 1. Fetch all categories of the Master Tenant
        const { data: masterCategories, error: fetchError } = await supabase
            .from('categories')
            .select('*')
            .eq('tenant_id', MASTER_TENANT_ID)
            .order('created_at', { ascending: true }); // Maintain creation order to guarantee Parent comes before Child

        if (fetchError || !masterCategories || masterCategories.length === 0) {
            console.error('[Provisioning] Error fetching master categories:', fetchError);
            return { success: false, error: 'Cannot fetch Master Categories' };
        }

        // 2. Algorithm to map Old ID -> New ID
        // Since Supabase UUIDs are generated by default on DB or client, we generate UUIDs on the client
        // to build mapping before insertion, preserving the Parent-Child tree.
        const idMapping: Record<string, string> = {}; // { old_id: new_uuid }

        const newCategoriesToInsert = masterCategories.map((cat: any) => {
            const newId = crypto.randomUUID();
            idMapping[cat.id] = newId;

            return {
                id: newId,
                tenant_id: newTenantId,
                name_vi: cat.name_vi,
                name_km: cat.name_km,
                name_en: cat.name_en,
                slug: `${cat.slug}-${newTenantId.split('-')[0]}`,
                description_vi: cat.description_vi,
                description_km: cat.description_km,
                description_en: cat.description_en,
                image_url: cat.image_url,
                module: cat.module,
                type: cat.type,
                // parent_id will be updated in the second pass
                parent_id: cat.parent_id,
                created_at: new Date().toISOString(),
            };
        });

        // 3. Second pass: Re-assign the new Parent ID
        newCategoriesToInsert.forEach((newCat: any) => {
            if (newCat.parent_id && idMapping[newCat.parent_id]) {
                newCat.parent_id = idMapping[newCat.parent_id];
            } else if (newCat.parent_id && !idMapping[newCat.parent_id]) {
                // Case when parent_id points to a Global Category (tenant_id = null)
                // Retain original parent_id as it points to the shared category
            }
        });

        // 4. Chunk insert to prevent payload overload (chunk into 50 records / batch)
        const chunkSize = 50;
        for (let i = 0; i < newCategoriesToInsert.length; i += chunkSize) {
            const chunk = newCategoriesToInsert.slice(i, i + chunkSize);
            const { error: insertError } = await supabase
                .from('categories')
                .insert(chunk);

            if (insertError) {
                console.error(`[Provisioning] Error inserting category chunk ${i}:`, insertError);
                return { success: false, error: 'Failed to insert cloned categories' };
            }
        }

        return { success: true };

    } catch (error) {
        console.error('[Provisioning] Unexpected error during category cloning:', error);
        return { success: false, error: 'Unexpected error' };
    }
}
